export type ScannerInstallKind = "built-in" | "native" | "python" | "npm" | "go" | "cargo" | "system";

export type ScannerCatalogEntry = {
  id: string;
  label: string;
  category: "built-in" | "sast" | "secrets" | "sca" | "iac";
  command?: string;
  version?: string;
  installKind: ScannerInstallKind;
  languages: string[];
  inputs: string[];
  parser: string;
  defaultEnabled: boolean;
  autoInstall: boolean;
  riskNotes: string;
};

export const scannerCatalog: ScannerCatalogEntry[] = [
  {
    id: "hermsec-heuristics",
    label: "HermSec heuristics",
    category: "built-in",
    installKind: "built-in",
    languages: ["all"],
    inputs: ["source", "config", "manifest", "lockfile"],
    parser: "hermsec",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Built into HermSec. Runs deterministic local checks without external processes.",
  },
  {
    id: "semgrep",
    label: "Semgrep",
    category: "sast",
    command: "semgrep",
    version: "1.167.0",
    installKind: "python",
    languages: ["javascript", "typescript", "java", "jsp", "python", "go", "php", "ruby", "rust", "c", "cpp", "csharp", "html", "terraform", "yaml"],
    inputs: ["source", "config"],
    parser: "semgrep-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Runs local rules only with metrics disabled.",
  },
  {
    id: "gitleaks",
    label: "Gitleaks",
    category: "secrets",
    command: "gitleaks",
    version: "v8.30.1",
    installKind: "native",
    languages: ["all"],
    inputs: ["source", "config", "git"],
    parser: "gitleaks-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Runs with redaction enabled; raw secrets are not persisted.",
  },
  {
    id: "trufflehog",
    label: "TruffleHog",
    category: "secrets",
    command: "trufflehog",
    version: "v3.90.8",
    installKind: "go",
    languages: ["all"],
    inputs: ["source", "git"],
    parser: "trufflehog-jsonl",
    defaultEnabled: false,
    autoInstall: false,
    riskNotes: "Deeper secret scan. Credential verification should stay disabled unless the user opts in.",
  },
  {
    id: "osv-scanner",
    label: "OSV-Scanner",
    category: "sca",
    command: "osv-scanner",
    version: "v2.4.0",
    installKind: "native",
    languages: ["javascript", "typescript", "python", "java", "go", "rust", "php", "ruby"],
    inputs: ["lockfile", "sbom"],
    parser: "osv-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Queries OSV advisory data for supported lockfiles and SBOMs.",
  },
  {
    id: "trivy",
    label: "Trivy",
    category: "sca",
    command: "trivy",
    version: "v0.66.0",
    installKind: "native",
    languages: ["all"],
    inputs: ["filesystem", "lockfile", "iac", "container"],
    parser: "trivy-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Filesystem scans use vulnerability, secret, and misconfiguration scanners.",
  },
  {
    id: "checkov",
    label: "Checkov",
    category: "iac",
    command: "checkov",
    version: "3.2.471",
    installKind: "python",
    languages: ["terraform", "yaml", "dockerfile"],
    inputs: ["iac", "workflow", "dockerfile"],
    parser: "checkov-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Static IaC scanner; does not run infrastructure commands.",
  },
  {
    id: "bandit",
    label: "Bandit",
    category: "sast",
    command: "bandit",
    version: "1.9.4",
    installKind: "python",
    languages: ["python"],
    inputs: ["source"],
    parser: "bandit-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Python AST security linter.",
  },
  {
    id: "pip-audit",
    label: "pip-audit",
    category: "sca",
    command: "pip-audit",
    version: "2.10.1",
    installKind: "python",
    languages: ["python"],
    inputs: ["requirements.txt", "requirements-dev.txt"],
    parser: "pip-audit-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Runs only against pinned requirements in HermSec scans.",
  },
  {
    id: "pmg",
    label: "SafeDep PMG npm audit",
    category: "sca",
    command: "pmg",
    version: "v0.19.1",
    installKind: "native",
    languages: ["javascript", "typescript"],
    inputs: ["package-lock.json", "npm-shrinkwrap.json"],
    parser: "npm-audit-json",
    defaultEnabled: true,
    autoInstall: true,
    riskNotes: "Wraps npm audit with install/fix/script commands blocked.",
  },
  {
    id: "retire",
    label: "Retire.js",
    category: "sca",
    command: "retire",
    version: "5.2.7",
    installKind: "npm",
    languages: ["javascript", "typescript", "html"],
    inputs: ["source", "package.json"],
    parser: "retire-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Detects vulnerable JavaScript libraries, including vendored frontend assets.",
  },
  {
    id: "findsecbugs",
    label: "FindSecBugs / SpotBugs",
    category: "sast",
    command: "spotbugs",
    version: "4.9.3",
    installKind: "system",
    languages: ["java", "jsp", "kotlin"],
    inputs: ["compiled-classes"],
    parser: "spotbugs-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Requires compiled classes; HermSec does not build the project automatically.",
  },
  {
    id: "dependency-check",
    label: "OWASP Dependency-Check",
    category: "sca",
    command: "dependency-check",
    version: "12.1.8",
    installKind: "system",
    languages: ["java", "javascript", "typescript", "python", "ruby", "dotnet"],
    inputs: ["manifest", "lockfile"],
    parser: "dependency-check-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Uses vulnerability databases and may require a warm local cache.",
  },
  {
    id: "psalm",
    label: "Psalm taint analysis",
    category: "sast",
    command: "psalm",
    version: "6.13.1",
    installKind: "system",
    languages: ["php"],
    inputs: ["source", "composer.json"],
    parser: "psalm-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Runs taint analysis when Psalm is already available for the PHP project.",
  },
  {
    id: "composer-audit",
    label: "Composer audit",
    category: "sca",
    command: "composer",
    installKind: "system",
    languages: ["php"],
    inputs: ["composer.lock"],
    parser: "composer-audit-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Reads Composer advisories from the lockfile; does not install packages.",
  },
  {
    id: "gosec",
    label: "gosec",
    category: "sast",
    command: "gosec",
    version: "v2.22.8",
    installKind: "go",
    languages: ["go"],
    inputs: ["source", "go.mod"],
    parser: "gosec-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Go AST/SSA security scanner.",
  },
  {
    id: "govulncheck",
    label: "govulncheck",
    category: "sca",
    command: "govulncheck",
    version: "v1.1.4",
    installKind: "go",
    languages: ["go"],
    inputs: ["go.mod", "source"],
    parser: "govulncheck-jsonl",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Official Go vulnerability checker; analyzes reachable vulnerable symbols.",
  },
  {
    id: "cargo-audit",
    label: "cargo-audit",
    category: "sca",
    command: "cargo",
    version: "0.21.2",
    installKind: "cargo",
    languages: ["rust"],
    inputs: ["Cargo.lock"],
    parser: "cargo-audit-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Audits Cargo.lock against RustSec advisories.",
  },
  {
    id: "brakeman",
    label: "Brakeman",
    category: "sast",
    command: "brakeman",
    version: "7.1.0",
    installKind: "system",
    languages: ["ruby"],
    inputs: ["rails-app"],
    parser: "brakeman-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Rails-aware SAST scanner.",
  },
  {
    id: "flawfinder",
    label: "Flawfinder",
    category: "sast",
    command: "flawfinder",
    version: "2.0.19",
    installKind: "python",
    languages: ["c", "cpp"],
    inputs: ["source"],
    parser: "flawfinder-sarif",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Fast lexical C/C++ security scan with CWE-compatible output.",
  },
  {
    id: "cppcheck",
    label: "Cppcheck",
    category: "sast",
    command: "cppcheck",
    version: "2.16.0",
    installKind: "system",
    languages: ["c", "cpp"],
    inputs: ["source"],
    parser: "cppcheck-text",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Static C/C++ analyzer. HermSec runs it without compiling the project.",
  },
  {
    id: "dotnet-vulnerable",
    label: ".NET vulnerable packages",
    category: "sca",
    command: "dotnet",
    installKind: "system",
    languages: ["csharp"],
    inputs: ["csproj", "sln", "packages.lock.json"],
    parser: "dotnet-json",
    defaultEnabled: true,
    autoInstall: false,
    riskNotes: "Uses dotnet package listing for vulnerable NuGet packages.",
  },
];

export function scannerCatalogEntry(id: string): ScannerCatalogEntry | undefined {
  return scannerCatalog.find((scanner) => scanner.id === id);
}
